# Generated by Django 4.2.16 on 2024-10-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0002_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnusedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
