# Generated by Django 4.2.16 on 2024-10-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0003_unusedkeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
